#!/bin/bash
# Create a Cloudflare Tunnel for paperscraper.miladlab.com and install a LaunchAgent.
# Requires a free Cloudflare account. DNS for miladlab.com stays at GoDaddy (CNAME only).
set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This installer only runs on your Mac (needs launchctl and cloudflared)." >&2
  echo "This shell is $(uname -s) ($(hostname)), not macOS." >&2
  echo "On the Mac, open Terminal.app (not Cursor Cloud) and run:" >&2
  echo "  cd \"\$HOME/Documents/Cannabis Paper Scraper\"" >&2
  echo "  ./scripts/macos/install_macos_cloudflared.sh" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HOSTNAME="${MACOS_TUNNEL_HOSTNAME:-paperscraper.miladlab.com}"
TUNNEL_NAME="${MACOS_TUNNEL_NAME:-paperscraper-miladlab}"
LABEL="com.mckenzian.cannabis-cloudflared"
PLIST_DIR="${HOME}/Library/LaunchAgents"
PLIST_PATH="${PLIST_DIR}/${LABEL}.plist"
CF_DIR="${HOME}/.cloudflared"
CONFIG_PATH="${CF_DIR}/config.yml"
LOG_DIR="${REPO_ROOT}/logs"
EXAMPLE="${REPO_ROOT}/scripts/macos/cloudflared-config.yml.example"

usage() {
  echo "Usage: $0 [--uninstall]"
  echo "Creates Cloudflare Tunnel ${TUNNEL_NAME} → http://127.0.0.1:8080 as ${HOSTNAME}."
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

uid="$(id -u)"
domain="gui/${uid}"

unload_agent() {
  launchctl bootout "${domain}/${LABEL}" >/dev/null 2>&1 || true
  launchctl unload "${PLIST_PATH}" >/dev/null 2>&1 || true
}

if [[ "${1:-}" == "--uninstall" ]]; then
  unload_agent
  rm -f "${PLIST_PATH}"
  echo "Removed ${LABEL} (tunnel credentials in ${CF_DIR} were left in place)."
  exit 0
fi

resolve_cloudflared() {
  if command -v cloudflared >/dev/null 2>&1; then
    command -v cloudflared
    return 0
  fi
  if [[ -x /opt/homebrew/bin/cloudflared ]]; then
    echo /opt/homebrew/bin/cloudflared
    return 0
  fi
  if [[ -x /usr/local/bin/cloudflared ]]; then
    echo /usr/local/bin/cloudflared
    return 0
  fi
  return 1
}

if ! CLOUDFLARED="$(resolve_cloudflared)"; then
  if command -v brew >/dev/null 2>&1; then
    echo "Installing cloudflared via Homebrew..."
    brew install cloudflared
    CLOUDFLARED="$(resolve_cloudflared)" || true
  fi
fi
if [[ -z "${CLOUDFLARED:-}" ]]; then
  echo "cloudflared is not installed. Install it from https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/ then re-run." >&2
  exit 1
fi

mkdir -p "${CF_DIR}" "${LOG_DIR}" "${PLIST_DIR}"

if [[ ! -f "${CF_DIR}/cert.pem" ]]; then
  echo "No Cloudflare tunnel certificate at ${CF_DIR}/cert.pem"
  echo "Run this once (opens a browser to authorize the tunnel):"
  echo "  ${CLOUDFLARED} tunnel login"
  echo "Then re-run: $0"
  exit 1
fi

if ! "${CLOUDFLARED}" tunnel list 2>/dev/null | grep -q "${TUNNEL_NAME}"; then
  echo "Creating tunnel ${TUNNEL_NAME}..."
  "${CLOUDFLARED}" tunnel create "${TUNNEL_NAME}"
fi

TUNNEL_UUID="$("${CLOUDFLARED}" tunnel list --output json 2>/dev/null | python3 -c "
import json, sys
name = sys.argv[1]
rows = json.load(sys.stdin)
if isinstance(rows, dict):
    rows = rows.get('tunnels') or rows.get('result') or []
for row in rows:
    if row.get('name') == name:
        print(row.get('id') or row.get('uuid') or '')
        break
" "${TUNNEL_NAME}" || true)"

if [[ -z "${TUNNEL_UUID}" ]]; then
  TUNNEL_UUID="$("${CLOUDFLARED}" tunnel list 2>/dev/null | awk -v name="${TUNNEL_NAME}" '$2 == name { print $1; exit }')"
fi
if [[ -z "${TUNNEL_UUID}" ]]; then
  echo "Could not resolve tunnel UUID for ${TUNNEL_NAME}. Run: ${CLOUDFLARED} tunnel list" >&2
  exit 1
fi

CRED_FILE="${CF_DIR}/${TUNNEL_UUID}.json"
if [[ ! -f "${CRED_FILE}" ]]; then
  echo "Expected credentials file ${CRED_FILE} after tunnel create." >&2
  exit 1
fi

cat > "${CONFIG_PATH}" <<EOF
# Generated by scripts/macos/install_macos_cloudflared.sh
tunnel: ${TUNNEL_UUID}
credentials-file: ${CRED_FILE}

ingress:
  - hostname: ${HOSTNAME}
    service: http://127.0.0.1:8080
  - service: http_status:404
EOF

cat > "${PLIST_PATH}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${CLOUDFLARED}</string>
    <string>tunnel</string>
    <string>--config</string>
    <string>${CONFIG_PATH}</string>
    <string>run</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${LOG_DIR}/cloudflared.launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>${LOG_DIR}/cloudflared.launchd.err.log</string>
</dict>
</plist>
EOF

unload_agent
if ! launchctl bootstrap "${domain}" "${PLIST_PATH}" 2>/dev/null; then
  launchctl load "${PLIST_PATH}"
fi

echo "Installed ${LABEL}"
echo "  tunnel:  ${TUNNEL_NAME}"
echo "  uuid:    ${TUNNEL_UUID}"
echo "  config:  ${CONFIG_PATH}"
echo
echo "Add this CNAME at GoDaddy (DNS only; do not change nameservers):"
echo "  Type:  CNAME"
echo "  Name:  paperscraper"
echo "  Value: ${TUNNEL_UUID}.cfargotunnel.com"
echo
echo "Site must already be listening on 127.0.0.1:8080:"
echo "  ${REPO_ROOT}/scripts/macos/install_macos_site.sh"
echo "See ${REPO_ROOT}/docs/macos-public-site.md"
